### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by bodzio166** [w74/billboard-api#1]
Hello!

Seems not to work anymore... What happened?

**Comment by w74** [comment]
The database has not been updated since the last commit 2 years ago.

**Comment by bodzio166** [comment]
Hello!

Can it be somehow updated?

**Comment by w74** [comment]
Probably not. It was a lot of manual work to pull the data as Billboard doesn't have any easy access to the info. Hope you find an alternative and good luck on your project!
